const DEFAULT_FILE_COUNT = 9;
const DEFAULT_FILE_LIMIT = 14;
const DEFAULT_GRAVITY = 980; // gravity is planet-wide (or level-wide) constant
const DEFAULT_REFERENCE_HEIGHT = 1080; // baseline screen height for normalization
const DEFAULT_POP_VELOCITY = -6000;
const DEFAULT_LAUNCH_VELOCITY = -1200;
const DEFAULT_LAUNCH_DESCENT_RATE = 200;
const DEFAULT_POINTER_POSITION = { x: -1, y: -1 };
const DEFAULT_DROP_INTERVAL = 700;
const DEFAULT_MAIN_TICKER_SPEED = 1;
const ACCELERATED_MAIN_TICKER_SPEED = 10;

export {
  DEFAULT_FILE_COUNT,
  DEFAULT_FILE_LIMIT,
  DEFAULT_GRAVITY,
  DEFAULT_REFERENCE_HEIGHT,
  DEFAULT_POP_VELOCITY,
  DEFAULT_LAUNCH_VELOCITY,
  DEFAULT_LAUNCH_DESCENT_RATE,
  DEFAULT_POINTER_POSITION,
  DEFAULT_DROP_INTERVAL,
  DEFAULT_MAIN_TICKER_SPEED,
  ACCELERATED_MAIN_TICKER_SPEED,
};
